doctrine:
    dbal:
        dbname:               symfony
        host:                 localhost
        port:                 3306
        user:                 root
        password:             
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: UTF8

        url:          mysql://root:@127.0.0.1:3306/symfony
        driver_class: App\DBAL\Driver\PDOMySql\Driver

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App